---
- name: add rancher chart repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"

- name: copy over values file
  template:
    src: "rancher_helm_values.yml.j2"
    dest: "/tmp/rancher_helm_values.yml"

#Not needed as running supported kubernetes
#- name: workaround for rancher chart bug with kubernetes 1.23
#  block:
#    - name: download stable chart
#      shell:
#        cmd: |
#          rm -rf /tmp/rancher
#          helm pull rancher-stable/rancher --destination /tmp/ --untar --untardir /tmp/ --version 2.6.2
#
#    - name: replace kubernetes version in chart
#      ansible.builtin.lineinfile:
#        path: /tmp/rancher/Chart.yaml
#        search_string: "kubeVersion"
#        line: 'kubeVersion: < v1.24.0-0'

- name: deploy rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    release_namespace: cattle-system
    create_namespace: yes
    wait: True
    values_files:
      - /tmp/rancher_helm_values.yml

- name: cleanup files
  file:
    name:
      - /tmp/rancher_helm_values.yml
      - /tmp/rancher
    state: absent
