---
- name: add "{{ role_name }}" chart repo
  kubernetes.core.helm_repository:
    name: "{{  role_chart_name.split('/')[0] | lower }}"
    repo_url: "{{ role_repo_url}}"

- name: Create "{{ role_name }}" namespace
  kubernetes.core.k8s:
    name: "{{ role_namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: create tls secret for "{{ role_name }}" ingress
  become: yes
  become_user: kube
  kubernetes.core.k8s:
    state: present
    template: "secret.yml.j2"

- name: copy over values file
  template:
    src: "{{ role_name }}_helm_values.yml.j2"
    dest: "/tmp/{{ role_name }}_helm_values.yml"

- name: deploy "{{ role_name }}"
  kubernetes.core.helm:
    name: "{{ role_name }}"
    chart_ref:
    release_namespace: "{{ role_namespace }}"
    create_namespace: no
    wait: True
    values_files: "/tmp/{{ role_name }}_helm_values.yml"

- name: cleanup files
  file:
    name: "/tmp/{{ role_name }}_helm_values.yml"
    state: absent
