---
#special Conditionals and vars
ansible_ssh_user: pi
ansible_python_interpreter: /bin/python3
local_user: "{{ lookup('env','USER') }}"

#metallb vars
metallb_ip_range: "192.168.78.50-192.168.78.200"
nginx_ingress_lb: "192.168.78.50"

public_cert: "-----BEGIN CERTIFICATE-----
MIIE8jCCA9qgAwIBAgIUUo5Wbn5uSDDPAHNU2NqPsdzIu9YwDQYJKoZIhvcNAQEL
BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MB4XDTIxMDYwOTA1MzAwMFoXDTM2MDYwNTA1MzAwMFowYjEZMBcGA1UEChMQQ2xv
dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvaEzgmfwzx4zoq9LMbQRcl/60nBjZYb7k2eQ
msCuS90u18neVvPOzmtyQqbGAV5hsTHk/im1UMmRCIoG6+coADe/e74IknF485ie
iXI4EIYes3vk/uItjLFAFsoBhkbfoUPeGdFSXJauq2LhA22q8G1SsxO/z2pRUbkp
JVKGcbZHEqnOYXgkmApf+nARWYPIpeY00eUYIOFtz321H9/EozBV5HDtQzqBVpAb
FBt4BqU54i3/82iEZi2St2s7FoQjRA2cxvj1SyfYWkxfm4GIw35PwNjkze9aGENM
dpgR3TxjzOIVXp+GOk4yfxEgLfrY10qn2cN3AdKkf5B00kbuqwIDAQABo4IBdDCC
AXAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSiM4Q8U4XznXKBynxrL6uxpC96KzAf
BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
YTB1BgNVHREEbjBsggwqLndhdHRlZWwuYmWCDSoud2F0dGVlbC5jb22CDSoud2F0
dGVlbC5kZXaCDCoud2F0dGVlbC5pb4IKd2F0dGVlbC5iZYILd2F0dGVlbC5jb22C
C3dhdHRlZWwuZGV2ggp3YXR0ZWVsLmlvMDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6
Ly9jcmwuY2xvdWRmbGFyZS5jb20vb3JpZ2luX2NhLmNybDANBgkqhkiG9w0BAQsF
AAOCAQEAMDBFcxtj4ZgcpSe1YUAISK7NXiFKXBBx+8l2qypf9ckoAJDld9AkQAEo
avRX86D1IMM1r8wK+644Xtk1NjWSNocfOGJwEOOOLgWMH58d0gg6E/CGYUeb0htl
UVJrTCP5WxMpWV6+pW/ib4c6wJhJmzbva7egaW0ngX8jZvGDlpxVT+vU7M7tytgK
5XYZdFAYv2x0bq/3cuYGdXb8W2Fezw3YrVWYy34o7F4X5Ao3ZuwTF5dH8zrKSKxK
4qnONUc7f2TquMY9gxukyJ/sfmrLLVwiKeTITIIiWKxvQEKyDlozEU93LMPD0zJ4
socSVWpzxK7RdxFZ8awbsAT7yDX7wA==
-----END CERTIFICATE-----"

public_cert_key: "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9oTOCZ/DPHjOi
r0sxtBFyX/rScGNlhvuTZ5CawK5L3S7Xyd5W887Oa3JCpsYBXmGxMeT+KbVQyZEI
igbr5ygAN797vgiScXjzmJ6JcjgQhh6ze+T+4i2MsUAWygGGRt+hQ94Z0VJclq6r
YuEDbarwbVKzE7/PalFRuSklUoZxtkcSqc5heCSYCl/6cBFZg8il5jTR5Rgg4W3P
fbUf38SjMFXkcO1DOoFWkBsUG3gGpTniLf/zaIRmLZK3azsWhCNEDZzG+PVLJ9ha
TF+bgYjDfk/A2OTN71oYQ0x2mBHdPGPM4hVen4Y6TjJ/ESAt+tjXSqfZw3cB0qR/
kHTSRu6rAgMBAAECggEABLw0QZLf4AQkjPDso0KYVu9Pn5af3MaonI8u/LZIA+vz
gf7v9uLirKPhOAnbEuis7tRMoA4hkXFfFkQAFT7x8EN0HB5sL1/3AbozZ0I7ZSo8
NQYoezbhpUw9yfPkYtp9NhUwRBvGfzpiBTSUYtYHuTY5pPAez4qbmjtR7DUp10gH
bqoP/07S/Yn34oqpJ3q5+baUhPFiPaPNgAXjBInVWuMSJ1KqCvRX851OvVGR5Kkr
POQuRxS8SNN5RdBJfCSiOrVCZ266QDRF5JRPPrmQ8Fwzb8+/pkN3aBgQfbTit5HQ
fiNHsg5VukOmBdLou0eHtTZAuSJAbsXx7HDOfxaKoQKBgQDkG5Wp8IjiJkidVzXt
RxnBz0g/+1xpqe82zuBMfI3Z18Muc+E/nsNcQWco+a/LyO8ws9Lkx2diDOQGNz8U
lBQZNEeEHM+eLRAjQs33ddApGgc1RPQ8NqmSDaffD3nWZ6LwGm8RxAeEPpjWPnea
5JhgRMQ0cEmWtRcjVYd9hx7tIQKBgQDU0SUXAiGBbe5G5hgqJpzLt3p9Agl5Wjvz
S3wpI3Xpvkw4CbxwTYHgBlYtXvelUm2zwpZeAV/z4QeE8m+unaNeZyR8NAkCL5v0
eDcF+yxNmw07LRnZ8W/pvjHmrEey0tPejBS2RjG8Rwyusi33I6TMxddB/1dfZXe9
LGx3WWK2SwKBgCDu8p7EgZ7VFCrTSo/lcgyPVskWC3Od+1GYcL3aRcir5Bwy0tSS
oXYSY0iBNCZh7lbDv7EUMRLw9YMIOu1Hq9cvuxuR5U/bBbdxj7copVMp1NyWBgUj
hzv1CMWlwFt6PwYXau3PtZ4cQ4i7IB2W34EWrJU9mQJPRvXtBVDUT1zBAoGBAIAI
o4vIGGhJvsSgwYD6YfKdm++BPjnn85FXpIcLcnEBr9E26kuWFcC1jzsUm2C2ypEP
TG+Z3CRZCbEOOeqPpC2zV9vxYkoSYn0dpdzPU8QMuFUVuSvJeU7iwhrJIwmOlTCa
jgtrB5kCFbs0Lzs0En2vuOVXvTUDUppZE5hqCl0pAoGBAJ4iqj6rR4onXKHIgzaj
9WfXYnPijUQArOjnY91ohVtCX/VNOs0pqIThqbEHSXa8RHC2W0QxShVPBpWv8GdL
ph9uv/LbEdhl6VrOOhjJ7Y4YC2L9618c36ahO4kR5OfwgoLTCRDlPUIBwzIwGSlE
wGJj3TMRrIjAbvVtIBARV59D
-----END PRIVATE KEY-----"







