---
#special Conditionals and vars
ansible_ssh_user: pi
ansible_python_interpreter: /bin/python3
local_user: "{{ lookup('env','USER') }}"

#metallb vars
metallb_ip_range: "192.168.78.50-192.168.78.200"
nginx_ingress_lb: "192.168.78.50"

public_cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4akNDQTlxZ0F3SUJBZ0lVVW81V2JuNXVT
RERQQUhOVTJOcVBzZHpJdTlZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZc3hDekFKQmdOVkJBWVRB
bFZUTVJrd0Z3WURWUVFLRXhCRGJHOTFaRVpzWVhKbExDQkpibU11TVRRdwpNZ1lEVlFRTEV5dERi
RzkxWkVac1lYSmxJRTl5YVdkcGJpQlRVMHdnUTJWeWRHbG1hV05oZEdVZ1FYVjBhRzl5CmFYUjVN
Ull3RkFZRFZRUUhFdzFUWVc0Z1JuSmhibU5wYzJOdk1STXdFUVlEVlFRSUV3cERZV3hwWm05eWJt
bGgKTUI0WERUSXhNRFl3T1RBMU16QXdNRm9YRFRNMk1EWXdOVEExTXpBd01Gb3dZakVaTUJjR0Ex
VUVDaE1RUTJ4dgpkV1JHYkdGeVpTd2dTVzVqTGpFZE1Cc0dBMVVFQ3hNVVEyeHZkV1JHYkdGeVpT
QlBjbWxuYVc0Z1EwRXhKakFrCkJnTlZCQU1USFVOc2IzVmtSbXhoY21VZ1QzSnBaMmx1SUVObGNu
UnBabWxqWVhSbE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZh
RXpnbWZ3eng0em9xOUxNYlFSY2wvNjBuQmpaWWI3azJlUQptc0N1UzkwdTE4bmVWdlBPem10eVFx
YkdBVjVoc1RIay9pbTFVTW1SQ0lvRzYrY29BRGUvZTc0SWtuRjQ4NWllCmlYSTRFSVllczN2ay91
SXRqTEZBRnNvQmhrYmZvVVBlR2RGU1hKYXVxMkxoQTIycThHMVNzeE8vejJwUlVia3AKSlZLR2Ni
WkhFcW5PWVhna21BcGYrbkFSV1lQSXBlWTAwZVVZSU9GdHozMjFIOS9Fb3pCVjVIRHRRenFCVnBB
YgpGQnQ0QnFVNTRpMy84MmlFWmkyU3QyczdGb1FqUkEyY3h2ajFTeWZZV2t4Zm00R0l3MzVQd05q
a3plOWFHRU5NCmRwZ1IzVHhqek9JVlhwK0dPazR5ZnhFZ0xmclkxMHFuMmNOM0FkS2tmNUIwMGti
dXF3SURBUUFCbzRJQmREQ0MKQVhBd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJR
R0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdR
V0JCU2lNNFE4VTRYem5YS0J5bnhyTDZ1eHBDOTZLekFmCkJnTlZIU01FR0RBV2dCUWs2Rk5YWFh3
MFFJZXA2NVRidXVFV2VQd3BwREJBQmdnckJnRUZCUWNCQVFRME1ESXcKTUFZSUt3WUJCUVVITUFH
R0pHaDBkSEE2THk5dlkzTndMbU5zYjNWa1pteGhjbVV1WTI5dEwyOXlhV2RwYmw5agpZVEIxQmdO
VkhSRUViakJzZ2d3cUxuZGhkSFJsWld3dVltV0NEU291ZDJGMGRHVmxiQzVqYjIyQ0RTb3VkMkYw
CmRHVmxiQzVrWlhhQ0RDb3VkMkYwZEdWbGJDNXBiNElLZDJGMGRHVmxiQzVpWllJTGQyRjBkR1Zs
YkM1amIyMkMKQzNkaGRIUmxaV3d1WkdWMmdncDNZWFIwWldWc0xtbHZNRGdHQTFVZEh3UXhNQzh3
TGFBcm9DbUdKMmgwZEhBNgpMeTlqY213dVkyeHZkV1JtYkdGeVpTNWpiMjB2YjNKcFoybHVYMk5o
TG1OeWJEQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBTURCRmN4dGo0WmdjcFNlMVlVQUlTSzdO
WGlGS1hCQngrOGwycXlwZjlja29BSkRsZDlBa1FBRW8KYXZSWDg2RDFJTU0xcjh3Sys2NDRYdGsx
TmpXU05vY2ZPR0p3RU9PT0xnV01INThkMGdnNkUvQ0dZVWViMGh0bApVVkpyVENQNVd4TXBXVjYr
cFcvaWI0YzZ3SmhKbXpidmE3ZWdhVzBuZ1g4alp2R0RscHhWVCt2VTdNN3R5dGdLCjVYWVpkRkFZ
djJ4MGJxLzNjdVlHZFhiOFcyRmV6dzNZclZXWXkzNG83RjRYNUFvM1p1d1RGNWRIOHpyS1NLeEsK
NHFuT05VYzdmMlRxdU1ZOWd4dWt5Si9zZm1yTExWd2lLZVRJVElJaVdLeHZRRUt5RGxvekVVOTNM
TVBEMHpKNApzb2NTVldwenhLN1JkeEZaOGF3YnNBVDd5RFg3d0E9PQotLS0tLUVORCBDRVJUSUZJ
Q0FURS0tLS0tCg=="

public_cert_key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
QVNDQktnd2dnU2tBZ0VBQW9JQkFRQzlvVE9DWi9EUEhqT2kKcjBzeHRCRnlYL3JTY0dObGh2dVRa
NUNhd0s1TDNTN1h5ZDVXODg3T2EzSkNwc1lCWG1HeE1lVCtLYlZReVpFSQppZ2JyNXlnQU43OTd2
Z2lTY1hqem1KNkpjamdRaGg2emUrVCs0aTJNc1VBV3lnR0dSdCtoUTk0WjBWSmNscTZyCll1RURi
YXJ3YlZLekU3L1BhbEZSdVNrbFVvWnh0a2NTcWM1aGVDU1lDbC82Y0JGWmc4aWw1alRSNVJnZzRX
M1AKZmJVZjM4U2pNRlhrY08xRE9vRldrQnNVRzNnR3BUbmlMZi96YUlSbUxaSzNhenNXaENORURa
ekcrUFZMSjloYQpURitiZ1lqRGZrL0EyT1RONzFvWVEweDJtQkhkUEdQTTRoVmVuNFk2VGpKL0VT
QXQrdGpYU3FmWnczY0IwcVIvCmtIVFNSdTZyQWdNQkFBRUNnZ0VBQkx3MFFaTGY0QVFralBEc28w
S1lWdTlQbjVhZjNNYW9uSTh1L0xaSUErdnoKZ2Y3djl1TGlyS1BoT0FuYkV1aXM3dFJNb0E0aGtY
RmZGa1FBRlQ3eDhFTjBIQjVzTDEvM0Fib3paMEk3WlNvOApOUVlvZXpiaHBVdzl5ZlBrWXRwOU5o
VXdSQnZHZnpwaUJUU1VZdFlIdVRZNXBQQWV6NHFibWp0UjdEVXAxMGdICmJxb1AvMDdTL1luMzRv
cXBKM3E1K2JhVWhQRmlQYVBOZ0FYakJJblZXdU1TSjFLcUN2Ulg4NTFPdlZHUjVLa3IKUE9RdVJ4
UzhTTk41UmRCSmZDU2lPclZDWjI2NlFEUkY1SlJQUHJtUThGd3piOCsvcGtOM2FCZ1FmYlRpdDVI
UQpmaU5Ic2c1VnVrT21CZExvdTBlSHRUWkF1U0pBYnNYeDdIRE9meGFLb1FLQmdRRGtHNVdwOElq
aUpraWRWelh0ClJ4bkJ6MGcvKzF4cHFlODJ6dUJNZkkzWjE4TXVjK0UvbnNOY1FXY28rYS9MeU84
d3M5TGt4MmRpRE9RR056OFUKbEJRWk5FZUVITStlTFJBalFzMzNkZEFwR2djMVJQUThOcW1TRGFm
ZkQzbldaNkx3R204UnhBZUVQcGpXUG5lYQo1SmhnUk1RMGNFbVd0UmNqVllkOWh4N3RJUUtCZ1FE
VTBTVVhBaUdCYmU1RzVoZ3FKcHpMdDNwOUFnbDVXanZ6ClMzd3BJM1hwdmt3NENieHdUWUhnQmxZ
dFh2ZWxVbTJ6d3BaZUFWL3o0UWVFOG0rdW5hTmVaeVI4TkFrQ0w1djAKZURjRit5eE5tdzA3TFJu
WjhXL3B2akhtckVleTB0UGVqQlMyUmpHOFJ3eXVzaTMzSTZUTXhkZEIvMWRmWlhlOQpMR3gzV1dL
MlN3S0JnQ0R1OHA3RWdaN1ZGQ3JUU28vbGNneVBWc2tXQzNPZCsxR1ljTDNhUmNpcjVCd3kwdFNT
Cm9YWVNZMGlCTkNaaDdsYkR2N0VVTVJMdzlZTUlPdTFIcTljdnV4dVI1VS9iQmJkeGo3Y29wVk1w
MU55V0JnVWoKaHp2MUNNV2x3RnQ2UHdZWGF1M1B0WjRjUTRpN0lCMlczNEVXckpVOW1RSlBSdlh0
QlZEVVQxekJBb0dCQUlBSQpvNHZJR0doSnZzU2d3WUQ2WWZLZG0rK0JQam5uODVGWHBJY0xjbkVC
cjlFMjZrdVdGY0MxanpzVW0yQzJ5cEVQClRHK1ozQ1JaQ2JFT09lcVBwQzJ6Vjl2eFlrb1NZbjBk
cGR6UFU4UU11RlVWdVN2SmVVN2l3aHJKSXdtT2xUQ2EKamd0ckI1a0NGYnMwTHpzMEVuMnZ1T1ZY
dlRVRFVwcFpFNWhxQ2wwcEFvR0JBSjRpcWo2clI0b25YS0hJZ3phago5V2ZYWW5QaWpVUUFyT2pu
WTkxb2hWdENYL1ZOT3MwcHFJVGhxYkVIU1hhOFJIQzJXMFF4U2hWUEJwV3Y4R2RMCnBoOXV2L0xi
RWRobDZWck9PaGpKN1k0WUMyTDk2MThjMzZhaE80a1I1T2Z3Z29MVENSRGxQVUlCd3pJd0dTbEUK
d0dKajNUTVJySWpBYnZWdElCQVJWNTlECi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"







