---
#special Conditionals and vars
ansible_ssh_user: pi
ansible_python_interpreter: /bin/python3
local_user: "{{ lookup('env','USER') }}"

#metallb vars
metallb_ip_range: "192.168.78.50-192.168.78.200"
nginx_ingress_lb: "192.168.78.50"

public_cert: "{{ vault_public_cert }}"
public_cert_key: "{{ vault_public_cert_key }}"

timezone: "Asia/Dubai"







