---
- name: upgrade packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: install pre-requirements
  ansible.builtin.package:
    name:
      - unzip
      - rng-tools
      - python3
      - python3-pip
      - xfsprogs
    state: present

- name: Copy rngd systemd template
  template:
    src: rngd.service.j2
    dest: /etc/systemd/system/rngd.service
    owner: root
    group: root
    mode: 0644

- name: Ensure that the rngd service is enabled and started at boot time
  service:
    name: rngd
    enabled: yes
    state: started

- name: set hostnames
  ansible.builtin.shell:
    cmd: |
      hostnamectl set-hostname "{{ ansible_host }}"

- name: Update the /etc/hosts file with node name
  tags: etchostsupdate
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
  register: etchostsupdate
  with_items: "{{groups['all']}}"

- name: disable swap
  shell: |
         sudo swapoff -a
         sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: be sure ufw is disabled and stopped
  systemd:
    name: ufw
    enabled: no
    state: stopped

