---
- name: add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: copy over values file
  template:
    src: "longhorn_helm_values.yml.j2"
    dest: "/tmp/longhorn_helm_values.yml"

- name: deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: yes
    wait: True
    update_repo_cache: yes

- name: cleanup files
  file:
    name: /tmp/longhorn_helm_values.yml
    state: absent
