---
- name: generate a kubeadm certificate-key
  shell:
    cmd: kubeadm certs certificate-key
  register: kubernetes_certificate_key

- name: Copy over kubeadmin config
  template:
    dest: /tmp/kubeadm-config.yaml
    src: kubeadm-config.yaml.j2

- name: initialize the cluster
  shell: |
    kubeadm init --config=/tmp/kubeadm-config.yaml --upload-certs
    touch cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory for kube user
  become: yes
  become_user: kube
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: "create .kube directory for {{ ansible_ssh_user }} user"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube
    mode: 0600

- name: "copies admin.conf to {{ ansible_ssh_user }} kube config"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_ssh_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    mode: 0600

- name: register discovery-token-ca-cert-hash
  shell:
    cmd: kubeadm token create  --print-join-command | awk  -F" " '{print $7}'
  register: kubernetes_discovery_token

- name: register join token
  shell:
    cmd: kubeadm token create  --print-join-command | awk  -F" " '{print $5}'
  register: kubernetes_join_token
