---
- name: copy over masters join
  template:
    src: kubernetes_master_join_command.j2
    dest: /tmp/kubernetes_master_join_command

- name: Changing perm of /tmp/kubernetes_master_join_command , adding "+x"
  file: dest=/tmp/kubernetes_master_join_command mode=a+x

- name: join masters to bootstrap node
#  throttle: 1
  shell:
    cmd: /tmp/kubernetes_master_join_command
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
