galaxy_info:
  role_name: rancher
  author: Pascal Watteel
  description: This role will deploy rancher on a kubernetes cluster
  license: GPLv2
  min_ansible_version: 2.9
  platforms:
    - name: Redhat
      versions:
        - 8
  galaxy_tags: []
dependencies: []
