---
- name: add jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: copy over values file
  template:
    src: "cert-manager_helm_values.yml.j2"
    dest: "/tmp/cert-manager_helm_values.yml"

- name: deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    wait: True
    values_files:
      - /tmp/cert-manager_helm_values.yml

- include_tasks: self-signedCA.yml
  when: certmanager_ca | bool == true

- include_tasks: ACME.yml
  when: certmanager_acme | bool == true

- include_tasks: ACME-dns.yml
  when: certmanager_acme_dns | bool  == true
