---
- block:
    - name: inlude vars for enabled apps
      include_vars:
        file: "{{ item }}.yml"
        name: "{{ item }}"

    - name: debug
      debug:
        msg: "{{ hostvars[inventory_hostname][item] }}"

    - name: add chart repo
      kubernetes.core.helm_repository:
        name: "{{ [item].role_chart_name.split('/')[0] | lower }}"
        repo_url: "{{ [item].role_repo_url }}"

    - name: Create namespace
      kubernetes.core.k8s:
        name: "{{ [item].role_namespace }}"
        api_version: v1
        kind: namespace
        state: present

    - name: create tls secret for ingress
      become: yes
      become_user: kube
      kubernetes.core.k8s:
        state: present
        template: "secret.yml.j2"

    - name: copy over values file
      template:
        src: "{{ [item].role_name}}_values.yaml.j2"
        dest: "/tmp/{{ [item].role_name}}_values.yaml"

    - name: deploy
      kubernetes.core.helm:
        name: "{{ [item].role_name}}"
        chart_ref: "{{ [item].role_chart_name }}"
        release_namespace: "{{ [item].role_namespace }}"
        create_namespace: no
        wait: True
        update_repo_cache: yes

    - name: cleanup files
      file:
        name: "/tmp/{{ [item].role_name }}_values.yaml"
        state: absent
  when: home_apps.heimdall
