---
- block:
    - name: Read in task specific vars
      include_vars:
        file: heimdall.yml
        name: heimdall

    - name: add chart repo
      kubernetes.core.helm_repository:
        name: "{{  heimdall.role_chart_name.split('/')[0] | lower }}"
        repo_url: "{{ heimdall.role_repo_url }}"

    - name: Create namespace
      kubernetes.core.k8s:
        name: "{{ heimdall.role_namespace }}"
        api_version: v1
        kind: namespace
        state: present

    - name: create tls secret for ingress
      become: yes
      become_user: kube
      kubernetes.core.k8s:
        state: present
        template: "secret.yml.j2"

    - name: copy over values file
      template:
        src: "{{ heimdall.role_name}}_values.yaml.j2"
        dest: "/tmp/{{ heimdall.role_name}}_values.yaml"

    - name: deploy
      kubernetes.core.helm:
        name: "{{ heimdall.role_name}}"
        chart_ref: "{{ heimdall.role_chart_name }}"
        release_namespace: "{{ heimdall.role_namespace }}"
        create_namespace: no
        wait: True
        update_repo_cache: yes

    - name: cleanup files
      file:
        name: "/tmp/{{ heimdall.role_name }}_values.yaml"
        state: absent
