---
- name: Create home-apps namespace
  kubernetes.core.k8s:
    name: home-apps
    api_version: v1
    kind: namespace
    state: present

- name: create tls secret for home-apps ingress
  become: yes
  become_user: kube
  kubernetes.core.k8s:
    state: present
    template: "secret.yml.j2"

- import_tasks: heimdall.yml
  when: deploy_heimdall

