- hosts: k8s_masters[0]
  become: no
  gather_facts: yes
  roles:
    - { role: rancher, when: "deploy_rancher" }
    - { role: kubernetes-dashboard, when: "deploy_kubernetes_dashboard" }
    - postgresql
