---
- hosts: kubernetes
  become: yes
  gather_facts: yes
  roles:
    - helm
  pre_tasks:
    - name: install prerequirements
      ansible.builtin.package:
        name:
          - git
          - jq
          - nfs-client
          - nfs-common
          - iscsi-initiator-utils
        state: latest

    - name: install needed pip modules
      ansible.builtin.pip:
        name:
          - openshift
          - pyyaml

    - name: inject iscsi initiator name
      ansible.builtin.shell:
        cmd: |
            echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi

    - name: set open-iscsi to start on boot and start service
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: yes

- hosts: k8s_masters[0]
  become: no
  gather_facts: yes
  roles:
    - calico
    - longhorn
    - metallb
    - cert-manager
    - nginx
    - rancher
