---
- hosts: kubernetes
  gather_facts: yes
  become: yes
  tasks:
    - name: cleanup existing kubeadm deployments
      ansible.builtin.shell:
        cmd: |
          kubeadm reset --force

    - name: remove cluster initialized
      become: yes
      file:
        path: $HOME/cluster_initialized.txt
        state: absent

    - name: remove old cni config
      become: yes
      file:
        path: /etc/cni/net.d/*
        state: absent



